/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedOrganizationIndexRouteImport } from './routes/_authenticated/organization.index'
import { Route as AuthenticatedSettingsTerritoryRouteImport } from './routes/_authenticated/settings.territory'
import { Route as AuthenticatedSettingsPlatformRouteImport } from './routes/_authenticated/settings.platform'
import { Route as AuthenticatedSettingsMastersRouteImport } from './routes/_authenticated/settings.masters'
import { Route as AuthenticatedSettingsGlobalRouteImport } from './routes/_authenticated/settings.global'
import { Route as AuthenticatedOrganizationUsersRouteImport } from './routes/_authenticated/organization.users'
import { Route as AuthenticatedOrganizationTreeRouteImport } from './routes/_authenticated/organization.tree'
import { Route as AuthenticatedOrganizationRolesRouteImport } from './routes/_authenticated/organization.roles'
import { Route as AuthenticatedOrganizationEmployeesRouteImport } from './routes/_authenticated/organization.employees'
import { Route as AuthenticatedOrganizationDepartmentsRouteImport } from './routes/_authenticated/organization.departments'
import { Route as AuthenticatedSettingsCompaniesIndexRouteImport } from './routes/_authenticated/settings.companies.index'
import { Route as ApiPublicWebhooksSlugRouteImport } from './routes/api/public/webhooks.$slug'
import { Route as ApiPublicIntegrationsProcessJobsRouteImport } from './routes/api/public/integrations.process-jobs'
import { Route as AuthenticatedSettingsCompaniesCompanyIdRouteImport } from './routes/_authenticated/settings.companies.$companyId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedOrganizationIndexRoute =
  AuthenticatedOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any)
const AuthenticatedSettingsTerritoryRoute =
  AuthenticatedSettingsTerritoryRouteImport.update({
    id: '/territory',
    path: '/territory',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPlatformRoute =
  AuthenticatedSettingsPlatformRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMastersRoute =
  AuthenticatedSettingsMastersRouteImport.update({
    id: '/masters',
    path: '/masters',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGlobalRoute =
  AuthenticatedSettingsGlobalRouteImport.update({
    id: '/global',
    path: '/global',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedOrganizationUsersRoute =
  AuthenticatedOrganizationUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any)
const AuthenticatedOrganizationTreeRoute =
  AuthenticatedOrganizationTreeRouteImport.update({
    id: '/tree',
    path: '/tree',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any)
const AuthenticatedOrganizationRolesRoute =
  AuthenticatedOrganizationRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any)
const AuthenticatedOrganizationEmployeesRoute =
  AuthenticatedOrganizationEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any)
const AuthenticatedOrganizationDepartmentsRoute =
  AuthenticatedOrganizationDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any)
const AuthenticatedSettingsCompaniesIndexRoute =
  AuthenticatedSettingsCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const ApiPublicWebhooksSlugRoute = ApiPublicWebhooksSlugRouteImport.update({
  id: '/api/public/webhooks/$slug',
  path: '/api/public/webhooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntegrationsProcessJobsRoute =
  ApiPublicIntegrationsProcessJobsRouteImport.update({
    id: '/api/public/integrations/process-jobs',
    path: '/api/public/integrations/process-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSettingsCompaniesCompanyIdRoute =
  AuthenticatedSettingsCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organization': typeof AuthenticatedOrganizationRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/organization/departments': typeof AuthenticatedOrganizationDepartmentsRoute
  '/organization/employees': typeof AuthenticatedOrganizationEmployeesRoute
  '/organization/roles': typeof AuthenticatedOrganizationRolesRoute
  '/organization/tree': typeof AuthenticatedOrganizationTreeRoute
  '/organization/users': typeof AuthenticatedOrganizationUsersRoute
  '/settings/global': typeof AuthenticatedSettingsGlobalRoute
  '/settings/masters': typeof AuthenticatedSettingsMastersRoute
  '/settings/platform': typeof AuthenticatedSettingsPlatformRoute
  '/settings/territory': typeof AuthenticatedSettingsTerritoryRoute
  '/organization/': typeof AuthenticatedOrganizationIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/companies/$companyId': typeof AuthenticatedSettingsCompaniesCompanyIdRoute
  '/api/public/integrations/process-jobs': typeof ApiPublicIntegrationsProcessJobsRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
  '/settings/companies/': typeof AuthenticatedSettingsCompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organization/departments': typeof AuthenticatedOrganizationDepartmentsRoute
  '/organization/employees': typeof AuthenticatedOrganizationEmployeesRoute
  '/organization/roles': typeof AuthenticatedOrganizationRolesRoute
  '/organization/tree': typeof AuthenticatedOrganizationTreeRoute
  '/organization/users': typeof AuthenticatedOrganizationUsersRoute
  '/settings/global': typeof AuthenticatedSettingsGlobalRoute
  '/settings/masters': typeof AuthenticatedSettingsMastersRoute
  '/settings/platform': typeof AuthenticatedSettingsPlatformRoute
  '/settings/territory': typeof AuthenticatedSettingsTerritoryRoute
  '/organization': typeof AuthenticatedOrganizationIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/companies/$companyId': typeof AuthenticatedSettingsCompaniesCompanyIdRoute
  '/api/public/integrations/process-jobs': typeof ApiPublicIntegrationsProcessJobsRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
  '/settings/companies': typeof AuthenticatedSettingsCompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/organization': typeof AuthenticatedOrganizationRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/organization/departments': typeof AuthenticatedOrganizationDepartmentsRoute
  '/_authenticated/organization/employees': typeof AuthenticatedOrganizationEmployeesRoute
  '/_authenticated/organization/roles': typeof AuthenticatedOrganizationRolesRoute
  '/_authenticated/organization/tree': typeof AuthenticatedOrganizationTreeRoute
  '/_authenticated/organization/users': typeof AuthenticatedOrganizationUsersRoute
  '/_authenticated/settings/global': typeof AuthenticatedSettingsGlobalRoute
  '/_authenticated/settings/masters': typeof AuthenticatedSettingsMastersRoute
  '/_authenticated/settings/platform': typeof AuthenticatedSettingsPlatformRoute
  '/_authenticated/settings/territory': typeof AuthenticatedSettingsTerritoryRoute
  '/_authenticated/organization/': typeof AuthenticatedOrganizationIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/companies/$companyId': typeof AuthenticatedSettingsCompaniesCompanyIdRoute
  '/api/public/integrations/process-jobs': typeof ApiPublicIntegrationsProcessJobsRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
  '/_authenticated/settings/companies/': typeof AuthenticatedSettingsCompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/organization'
    | '/settings'
    | '/organization/departments'
    | '/organization/employees'
    | '/organization/roles'
    | '/organization/tree'
    | '/organization/users'
    | '/settings/global'
    | '/settings/masters'
    | '/settings/platform'
    | '/settings/territory'
    | '/organization/'
    | '/settings/'
    | '/settings/companies/$companyId'
    | '/api/public/integrations/process-jobs'
    | '/api/public/webhooks/$slug'
    | '/settings/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/organization/departments'
    | '/organization/employees'
    | '/organization/roles'
    | '/organization/tree'
    | '/organization/users'
    | '/settings/global'
    | '/settings/masters'
    | '/settings/platform'
    | '/settings/territory'
    | '/organization'
    | '/settings'
    | '/settings/companies/$companyId'
    | '/api/public/integrations/process-jobs'
    | '/api/public/webhooks/$slug'
    | '/settings/companies'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/organization'
    | '/_authenticated/settings'
    | '/_authenticated/organization/departments'
    | '/_authenticated/organization/employees'
    | '/_authenticated/organization/roles'
    | '/_authenticated/organization/tree'
    | '/_authenticated/organization/users'
    | '/_authenticated/settings/global'
    | '/_authenticated/settings/masters'
    | '/_authenticated/settings/platform'
    | '/_authenticated/settings/territory'
    | '/_authenticated/organization/'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/companies/$companyId'
    | '/api/public/integrations/process-jobs'
    | '/api/public/webhooks/$slug'
    | '/_authenticated/settings/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicIntegrationsProcessJobsRoute: typeof ApiPublicIntegrationsProcessJobsRoute
  ApiPublicWebhooksSlugRoute: typeof ApiPublicWebhooksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/organization/': {
      id: '/_authenticated/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof AuthenticatedOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationRoute
    }
    '/_authenticated/settings/territory': {
      id: '/_authenticated/settings/territory'
      path: '/territory'
      fullPath: '/settings/territory'
      preLoaderRoute: typeof AuthenticatedSettingsTerritoryRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/platform': {
      id: '/_authenticated/settings/platform'
      path: '/platform'
      fullPath: '/settings/platform'
      preLoaderRoute: typeof AuthenticatedSettingsPlatformRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/masters': {
      id: '/_authenticated/settings/masters'
      path: '/masters'
      fullPath: '/settings/masters'
      preLoaderRoute: typeof AuthenticatedSettingsMastersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/global': {
      id: '/_authenticated/settings/global'
      path: '/global'
      fullPath: '/settings/global'
      preLoaderRoute: typeof AuthenticatedSettingsGlobalRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/organization/users': {
      id: '/_authenticated/organization/users'
      path: '/users'
      fullPath: '/organization/users'
      preLoaderRoute: typeof AuthenticatedOrganizationUsersRouteImport
      parentRoute: typeof AuthenticatedOrganizationRoute
    }
    '/_authenticated/organization/tree': {
      id: '/_authenticated/organization/tree'
      path: '/tree'
      fullPath: '/organization/tree'
      preLoaderRoute: typeof AuthenticatedOrganizationTreeRouteImport
      parentRoute: typeof AuthenticatedOrganizationRoute
    }
    '/_authenticated/organization/roles': {
      id: '/_authenticated/organization/roles'
      path: '/roles'
      fullPath: '/organization/roles'
      preLoaderRoute: typeof AuthenticatedOrganizationRolesRouteImport
      parentRoute: typeof AuthenticatedOrganizationRoute
    }
    '/_authenticated/organization/employees': {
      id: '/_authenticated/organization/employees'
      path: '/employees'
      fullPath: '/organization/employees'
      preLoaderRoute: typeof AuthenticatedOrganizationEmployeesRouteImport
      parentRoute: typeof AuthenticatedOrganizationRoute
    }
    '/_authenticated/organization/departments': {
      id: '/_authenticated/organization/departments'
      path: '/departments'
      fullPath: '/organization/departments'
      preLoaderRoute: typeof AuthenticatedOrganizationDepartmentsRouteImport
      parentRoute: typeof AuthenticatedOrganizationRoute
    }
    '/_authenticated/settings/companies/': {
      id: '/_authenticated/settings/companies/'
      path: '/companies'
      fullPath: '/settings/companies/'
      preLoaderRoute: typeof AuthenticatedSettingsCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/api/public/webhooks/$slug': {
      id: '/api/public/webhooks/$slug'
      path: '/api/public/webhooks/$slug'
      fullPath: '/api/public/webhooks/$slug'
      preLoaderRoute: typeof ApiPublicWebhooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/process-jobs': {
      id: '/api/public/integrations/process-jobs'
      path: '/api/public/integrations/process-jobs'
      fullPath: '/api/public/integrations/process-jobs'
      preLoaderRoute: typeof ApiPublicIntegrationsProcessJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/companies/$companyId': {
      id: '/_authenticated/settings/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/settings/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedSettingsCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
  }
}

interface AuthenticatedOrganizationRouteChildren {
  AuthenticatedOrganizationDepartmentsRoute: typeof AuthenticatedOrganizationDepartmentsRoute
  AuthenticatedOrganizationEmployeesRoute: typeof AuthenticatedOrganizationEmployeesRoute
  AuthenticatedOrganizationRolesRoute: typeof AuthenticatedOrganizationRolesRoute
  AuthenticatedOrganizationTreeRoute: typeof AuthenticatedOrganizationTreeRoute
  AuthenticatedOrganizationUsersRoute: typeof AuthenticatedOrganizationUsersRoute
  AuthenticatedOrganizationIndexRoute: typeof AuthenticatedOrganizationIndexRoute
}

const AuthenticatedOrganizationRouteChildren: AuthenticatedOrganizationRouteChildren =
  {
    AuthenticatedOrganizationDepartmentsRoute:
      AuthenticatedOrganizationDepartmentsRoute,
    AuthenticatedOrganizationEmployeesRoute:
      AuthenticatedOrganizationEmployeesRoute,
    AuthenticatedOrganizationRolesRoute: AuthenticatedOrganizationRolesRoute,
    AuthenticatedOrganizationTreeRoute: AuthenticatedOrganizationTreeRoute,
    AuthenticatedOrganizationUsersRoute: AuthenticatedOrganizationUsersRoute,
    AuthenticatedOrganizationIndexRoute: AuthenticatedOrganizationIndexRoute,
  }

const AuthenticatedOrganizationRouteWithChildren =
  AuthenticatedOrganizationRoute._addFileChildren(
    AuthenticatedOrganizationRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsGlobalRoute: typeof AuthenticatedSettingsGlobalRoute
  AuthenticatedSettingsMastersRoute: typeof AuthenticatedSettingsMastersRoute
  AuthenticatedSettingsPlatformRoute: typeof AuthenticatedSettingsPlatformRoute
  AuthenticatedSettingsTerritoryRoute: typeof AuthenticatedSettingsTerritoryRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsCompaniesCompanyIdRoute: typeof AuthenticatedSettingsCompaniesCompanyIdRoute
  AuthenticatedSettingsCompaniesIndexRoute: typeof AuthenticatedSettingsCompaniesIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsGlobalRoute: AuthenticatedSettingsGlobalRoute,
  AuthenticatedSettingsMastersRoute: AuthenticatedSettingsMastersRoute,
  AuthenticatedSettingsPlatformRoute: AuthenticatedSettingsPlatformRoute,
  AuthenticatedSettingsTerritoryRoute: AuthenticatedSettingsTerritoryRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSettingsCompaniesCompanyIdRoute:
    AuthenticatedSettingsCompaniesCompanyIdRoute,
  AuthenticatedSettingsCompaniesIndexRoute:
    AuthenticatedSettingsCompaniesIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicIntegrationsProcessJobsRoute: ApiPublicIntegrationsProcessJobsRoute,
  ApiPublicWebhooksSlugRoute: ApiPublicWebhooksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
