/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsTerritoryRouteImport } from './routes/_authenticated/settings.territory'
import { Route as AuthenticatedSettingsMastersRouteImport } from './routes/_authenticated/settings.masters'
import { Route as AuthenticatedSettingsGlobalRouteImport } from './routes/_authenticated/settings.global'
import { Route as AuthenticatedSettingsCompaniesRouteImport } from './routes/_authenticated/settings.companies'
import { Route as AuthenticatedSettingsCompaniesCompanyIdRouteImport } from './routes/_authenticated/settings.companies.$companyId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTerritoryRoute =
  AuthenticatedSettingsTerritoryRouteImport.update({
    id: '/territory',
    path: '/territory',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMastersRoute =
  AuthenticatedSettingsMastersRouteImport.update({
    id: '/masters',
    path: '/masters',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsGlobalRoute =
  AuthenticatedSettingsGlobalRouteImport.update({
    id: '/global',
    path: '/global',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCompaniesRoute =
  AuthenticatedSettingsCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCompaniesCompanyIdRoute =
  AuthenticatedSettingsCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedSettingsCompaniesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/settings/companies': typeof AuthenticatedSettingsCompaniesRouteWithChildren
  '/settings/global': typeof AuthenticatedSettingsGlobalRoute
  '/settings/masters': typeof AuthenticatedSettingsMastersRoute
  '/settings/territory': typeof AuthenticatedSettingsTerritoryRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/settings/companies/$companyId': typeof AuthenticatedSettingsCompaniesCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings/companies': typeof AuthenticatedSettingsCompaniesRouteWithChildren
  '/settings/global': typeof AuthenticatedSettingsGlobalRoute
  '/settings/masters': typeof AuthenticatedSettingsMastersRoute
  '/settings/territory': typeof AuthenticatedSettingsTerritoryRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/settings/companies/$companyId': typeof AuthenticatedSettingsCompaniesCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/settings/companies': typeof AuthenticatedSettingsCompaniesRouteWithChildren
  '/_authenticated/settings/global': typeof AuthenticatedSettingsGlobalRoute
  '/_authenticated/settings/masters': typeof AuthenticatedSettingsMastersRoute
  '/_authenticated/settings/territory': typeof AuthenticatedSettingsTerritoryRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/settings/companies/$companyId': typeof AuthenticatedSettingsCompaniesCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/settings/companies'
    | '/settings/global'
    | '/settings/masters'
    | '/settings/territory'
    | '/settings/'
    | '/settings/companies/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/settings/companies'
    | '/settings/global'
    | '/settings/masters'
    | '/settings/territory'
    | '/settings'
    | '/settings/companies/$companyId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/settings/companies'
    | '/_authenticated/settings/global'
    | '/_authenticated/settings/masters'
    | '/_authenticated/settings/territory'
    | '/_authenticated/settings/'
    | '/_authenticated/settings/companies/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/territory': {
      id: '/_authenticated/settings/territory'
      path: '/territory'
      fullPath: '/settings/territory'
      preLoaderRoute: typeof AuthenticatedSettingsTerritoryRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/masters': {
      id: '/_authenticated/settings/masters'
      path: '/masters'
      fullPath: '/settings/masters'
      preLoaderRoute: typeof AuthenticatedSettingsMastersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/global': {
      id: '/_authenticated/settings/global'
      path: '/global'
      fullPath: '/settings/global'
      preLoaderRoute: typeof AuthenticatedSettingsGlobalRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/companies': {
      id: '/_authenticated/settings/companies'
      path: '/companies'
      fullPath: '/settings/companies'
      preLoaderRoute: typeof AuthenticatedSettingsCompaniesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/companies/$companyId': {
      id: '/_authenticated/settings/companies/$companyId'
      path: '/$companyId'
      fullPath: '/settings/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedSettingsCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedSettingsCompaniesRoute
    }
  }
}

interface AuthenticatedSettingsCompaniesRouteChildren {
  AuthenticatedSettingsCompaniesCompanyIdRoute: typeof AuthenticatedSettingsCompaniesCompanyIdRoute
}

const AuthenticatedSettingsCompaniesRouteChildren: AuthenticatedSettingsCompaniesRouteChildren =
  {
    AuthenticatedSettingsCompaniesCompanyIdRoute:
      AuthenticatedSettingsCompaniesCompanyIdRoute,
  }

const AuthenticatedSettingsCompaniesRouteWithChildren =
  AuthenticatedSettingsCompaniesRoute._addFileChildren(
    AuthenticatedSettingsCompaniesRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsCompaniesRoute: typeof AuthenticatedSettingsCompaniesRouteWithChildren
  AuthenticatedSettingsGlobalRoute: typeof AuthenticatedSettingsGlobalRoute
  AuthenticatedSettingsMastersRoute: typeof AuthenticatedSettingsMastersRoute
  AuthenticatedSettingsTerritoryRoute: typeof AuthenticatedSettingsTerritoryRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsCompaniesRoute:
    AuthenticatedSettingsCompaniesRouteWithChildren,
  AuthenticatedSettingsGlobalRoute: AuthenticatedSettingsGlobalRoute,
  AuthenticatedSettingsMastersRoute: AuthenticatedSettingsMastersRoute,
  AuthenticatedSettingsTerritoryRoute: AuthenticatedSettingsTerritoryRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
